# Generated by Django 2.2.6 on 2019-10-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saludar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='greet',
            name='name',
        ),
        migrations.AddField(
            model_name='greet',
            name='name_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saludar.Name'),
        ),
    ]
